// Mocks generated by Mockito 5.0.10 from annotations
// in delvetro_erp/test/app/modules/cadastro_servicos/cadastro_servicos_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:delvetro_erp/app/modules/cadastro-servicos/models/servicos_model.dart'
    as _i4;
import 'package:delvetro_erp/app/modules/cadastro-servicos/repository/cadastro_servicos_repository_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ICadastroServicosRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICadastroServicosRepository extends _i1.Mock
    implements _i2.ICadastroServicosRepository {
  MockICadastroServicosRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> salvarServico(_i4.ServicosModel? servicosModel) =>
      (super.noSuchMethod(Invocation.method(#salvarServico, [servicosModel]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<void> atualizarServico(_i4.ServicosModel? servicosModel) =>
      (super.noSuchMethod(Invocation.method(#atualizarServico, [servicosModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.Future<List<_i4.ServicosModel>> getListaServicos() =>
      (super.noSuchMethod(Invocation.method(#getListaServicos, []),
              returnValue:
                  Future<List<_i4.ServicosModel>>.value(<_i4.ServicosModel>[]))
          as _i3.Future<List<_i4.ServicosModel>>);
}
