// Mocks generated by Mockito 5.0.10 from annotations
// in delvetro_erp/test/app/modules/cadastro_cliente/cadastro_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:delvetro_erp/app/modules/cadastro_cliente/repositories/cadastro_cliente_repository_interface.dart'
    as _i2;
import 'package:delvetro_erp/app/shared/models/cliente_models.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ICadastroClienteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICadastroClienteRepository extends _i1.Mock
    implements _i2.ICadastroClienteRepository {
  MockICadastroClienteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> salvarCliente(_i4.ClienteModel? cliente) =>
      (super.noSuchMethod(Invocation.method(#salvarCliente, [cliente]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> alterarCliente(_i4.ClienteModel? cliente) =>
      (super.noSuchMethod(Invocation.method(#alterarCliente, [cliente]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
